Repository jkayodeabusi/bth-devops, pull requests merged in 2022-04, with the labels that each got.

#5 This comment is from Arinze
  group-1
Labels: bug

#12 membergroup2
  group-2
Labels: documentation

#14 Nafeesah has just saved to group-1
  group-1
Labels: enhancement

#13 This is Bisi commit
  group-1
Labels: enhancement

#10 This is my comment, don't touch the dial
  group-1
Labels: bug

#17 Dan updated grou-3 file
  group-2
  group-3
Labels: bug, enhancement

#9 chi comment
  group-2
Labels: bug

#7 abbey update grp2
  group-2
Labels: bug

#6 This is for ugo
  group-2
Labels: documentation
